/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.screens.members;

import gui.listeners.LoansListener;
import gui.listeners.MembersListener;
import gui.listeners.ReservationsListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myLibraryProject.Member;
import myLibraryProject.Publication;


public class MembersFrame extends javax.swing.JFrame {

    private final MembersListener membersListener;
    private final LoansListener loansListener;
    private final ReservationsListener reservationsListener;
    private final List<Publication> publications;
    

    /**
     * Creates new form AddMemberFrame
     *
     * @param membersListener
     * @param loansListener
     * @param reservationsListener
     * @param publications
     */
    public MembersFrame(MembersListener membersListener, LoansListener loansListener,ReservationsListener reservationsListener,List<Publication> publications) {
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.membersListener = membersListener;
        this.loansListener = loansListener;
        this.reservationsListener = reservationsListener;
        this.publications = publications;
        initView();
    }

    private void initView() {
        DefaultListModel<Member> membersListModel = new DefaultListModel<>();
        int i = 0;
        for (Member member : membersListener.getMembers()) {
            membersListModel.add(i++, member);
        }
        membersList.setModel(membersListModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMemberButtion3 = new javax.swing.JButton();
        addMemberButtion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        membersList = new javax.swing.JList();
        newLoanButton = new javax.swing.JButton();
        memberLoansButton = new javax.swing.JButton();
        newReservationButton = new javax.swing.JButton();
        memberReservationsButton = new javax.swing.JButton();

        addMemberButtion3.setText("New Loan");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addMemberButtion.setText("Add Member");
        addMemberButtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberButtionActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(membersList);

        newLoanButton.setText("New Loan");
        newLoanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLoanButtonActionPerformed(evt);
            }
        });

        memberLoansButton.setText("Member Loans");
        memberLoansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberLoansButtonActionPerformed(evt);
            }
        });

        newReservationButton.setText("New Reservation");
        newReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newReservationButtonActionPerformed(evt);
            }
        });

        memberReservationsButton.setText("Member Reservations");
        memberReservationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberReservationsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(memberReservationsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newReservationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memberLoansButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newLoanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addMemberButtion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addMemberButtion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newLoanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(memberLoansButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newReservationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(memberReservationsButton)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMemberButtionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberButtionActionPerformed
        AddMemberFrame addMemberFrame = new AddMemberFrame(membersListener);

        addMemberFrame.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                super.componentHidden(e); //To change body of generated methods, choose Tools | Templates.
                initView();
                setVisible(true);
            }

        });
        addMemberFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_addMemberButtionActionPerformed

    private void newLoanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLoanButtonActionPerformed
        int index = membersList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "You should select a Member first");
            return;
        }

        AddLoanFrame addLoanFrame = new AddLoanFrame(loansListener, publications, membersListener.getMembers().get(index));
        addLoanFrame.addComponentListener(new ComponentAdapter() {

            @Override
            public void componentHidden(ComponentEvent e) {
                super.componentHidden(e); //To change body of generated methods, choose Tools | Templates.
                setVisible(true);
            }

        });
        addLoanFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_newLoanButtonActionPerformed

    private void memberLoansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberLoansButtonActionPerformed
        int index = membersList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "You should select a Member first");
            return;
        }
        MemberLoansFrame memberLoansFrame = new MemberLoansFrame(loansListener, publications, membersListener.getMembers().get(index));
        memberLoansFrame.addComponentListener(new ComponentAdapter() {

            @Override
            public void componentHidden(ComponentEvent e) {
                super.componentHidden(e); //To change body of generated methods, choose Tools | Templates.
                setVisible(true);
            }

        });
        memberLoansFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_memberLoansButtonActionPerformed

    private void newReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newReservationButtonActionPerformed
        int index = membersList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "You should select a Member first");
            return;
        }
        AddReservationFrame addReservationsFrame = new AddReservationFrame(reservationsListener, publications, membersListener.getMembers().get(index));
        addReservationsFrame.addComponentListener(new ComponentAdapter() {

            @Override
            public void componentHidden(ComponentEvent e) {
                super.componentHidden(e); //To change body of generated methods, choose Tools | Templates.
                setVisible(true);
            }

        });
        addReservationsFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_newReservationButtonActionPerformed

    private void memberReservationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberReservationsButtonActionPerformed
        int index = membersList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "You should select a Member first");
            return;
        }
        MemberReservationsFrame membersReservationsFrame = new MemberReservationsFrame(reservationsListener, membersListener.getMembers().get(index));
        membersReservationsFrame.addComponentListener(new ComponentAdapter() {

            @Override
            public void componentHidden(ComponentEvent e) {
                super.componentHidden(e); //To change body of generated methods, choose Tools | Templates.
                setVisible(true);
            }

        });
        membersReservationsFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_memberReservationsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMemberButtion;
    private javax.swing.JButton addMemberButtion3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton memberLoansButton;
    private javax.swing.JButton memberReservationsButton;
    private javax.swing.JList membersList;
    private javax.swing.JButton newLoanButton;
    private javax.swing.JButton newReservationButton;
    // End of variables declaration//GEN-END:variables
}
