/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.screens.members;

import gui.listeners.LoansListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myLibraryProject.Copy;
import myLibraryProject.Loan;
import myLibraryProject.Member;
import myLibraryProject.Publication;

public class MemberLoansFrame extends javax.swing.JFrame {

    LoansListener listener;
    private final List<Publication> publications;
    private final Member selectedMember;

    
    public MemberLoansFrame(LoansListener listener, List<Publication> publications, Member selectedMember) {
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.listener = listener;
        this.publications = publications;
        this.selectedMember = selectedMember;
        initViews();
    }

    private void initViews() {
        DefaultListModel<Loan> loansListModel = new DefaultListModel<>();
        
        int i = 0;
        for (Loan loan : listener.getLoans()) {
            if (selectedMember == null || loan.getMember().equals(selectedMember)) {
                loansListModel.add(i++, loan);
            }
        }
        loansList.setModel(loansListModel);
        if(selectedMember == null){
            returnLoanButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        loansList = new javax.swing.JList();
        returnLoanButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(loansList);

        returnLoanButton.setText("Return Loan");
        returnLoanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnLoanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnLoanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnLoanButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnLoanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnLoanButtonActionPerformed
        // TODO add your handling code here:
        if(loansList.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "You should select a loan first");
            return;
        }
        Loan loan= listener.getLoans().get(loansList.getSelectedIndex());
        Copy copy = loan.getCopy();
        
        selectedMember.returnIt(copy);
        listener.onLoanReturned(loan);
        initViews();
    }//GEN-LAST:event_returnLoanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList loansList;
    private javax.swing.JButton returnLoanButton;
    // End of variables declaration//GEN-END:variables
}
