/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.screens.members;

import gui.listeners.ReservationsListener;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myLibraryProject.Member;
import myLibraryProject.Reservation;

public class MemberReservationsFrame extends javax.swing.JFrame {

    private final ReservationsListener listener;
    private final Member selectedMember;

    public MemberReservationsFrame(ReservationsListener listener, Member selectedMember) {
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.listener = listener;
        this.selectedMember = selectedMember;
        initViews();
    }

    private void initViews() {
        DefaultListModel model = new DefaultListModel();
        int i = 0;
        for (Reservation reservation : listener.getReservations()) {
            if (selectedMember == null || reservation.getMember().equals(selectedMember)) {
                model.add(i++, reservation);
            }
        }
        reservationsList.setModel(model);
        if (selectedMember == null) {
            pickupReservation.setEnabled(false);
            cancelReservation.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reservationsList = new javax.swing.JList();
        pickupReservation = new javax.swing.JButton();
        cancelReservation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(reservationsList);

        pickupReservation.setText("Pickup");
        pickupReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupReservationActionPerformed(evt);
            }
        });

        cancelReservation.setText("Cancel");
        cancelReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pickupReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pickupReservation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelReservation)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pickupReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupReservationActionPerformed

        int index = reservationsList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "You must select a reservation first!");
            return;
        }
        Reservation selectedReservation = listener.getReservations().get(index);
        selectedMember.pickupReservation(selectedReservation);
        listener.onReservationPickedUp(selectedReservation);
        initViews();
    }//GEN-LAST:event_pickupReservationActionPerformed

    private void cancelReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationActionPerformed
        int index = reservationsList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "You must select a reservation first!");
            return;
        }
        Reservation selectedReservation = listener.getReservations().get(index);
        selectedMember.cancelReservation(selectedReservation);
        listener.onReservationPickedUp(selectedReservation);
        initViews();
    }//GEN-LAST:event_cancelReservationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelReservation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pickupReservation;
    private javax.swing.JList reservationsList;
    // End of variables declaration//GEN-END:variables
}
