/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.screens.authors;

import gui.listeners.AuthorsListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myLibraryProject.Author;


public class AuthorsFrame extends javax.swing.JFrame {

    private AuthorsListener listener;

    /**
     * Creates new form AuthorsFrame
     * @param listener
     */
    public AuthorsFrame(AuthorsListener listener) {
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.listener = listener;
        initView();
    }

    private void initView() {
          DefaultListModel<Author> authorsListModel = new DefaultListModel<>();
        int i = 0;
        for (Author author : listener.getAuthors()) {
            authorsListModel.add(i++, author);
        }
        authorsList.setModel(authorsListModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        authorsList = new javax.swing.JList();
        addAuthorButtion = new javax.swing.JButton();
        authorBooksButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(authorsList);

        addAuthorButtion.setText("Add Author");
        addAuthorButtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorButtionActionPerformed(evt);
            }
        });

        authorBooksButton.setText("View Books");
        authorBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorBooksButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addAuthorButtion)
                    .addComponent(authorBooksButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addAuthorButtion)
                        .addGap(18, 18, 18)
                        .addComponent(authorBooksButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAuthorButtionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorButtionActionPerformed
        AddAuthorFrame addauthorFrame = new AddAuthorFrame(listener);

        addauthorFrame.addComponentListener(new ComponentAdapter() {

            @Override
            public void componentHidden(ComponentEvent e) {
                super.componentHidden(e); //To change body of generated methods, choose Tools | Templates.
                initView();
                setVisible(true);
            }

        });
        addauthorFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_addAuthorButtionActionPerformed

    private void authorBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorBooksButtonActionPerformed
        int index = authorsList.getSelectedIndex();
        if(index==-1){
            JOptionPane.showMessageDialog(null, "You should select an author first!");
            return;
        }
        AuthorDetailsFrame authorBooksFrame = new AuthorDetailsFrame(listener.getAuthors().get(index));

        authorBooksFrame.addComponentListener(new ComponentAdapter() {

            @Override
            public void componentHidden(ComponentEvent e) {
                super.componentHidden(e); //To change body of generated methods, choose Tools | Templates.
                initView();
                setVisible(true);
            }

        });
        authorBooksFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_authorBooksButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAuthorButtion;
    private javax.swing.JButton authorBooksButton;
    private javax.swing.JList authorsList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
